Repository microsoft/spring-data-cosmosdb, pull requests merged in 2018-08, with the labels that each got.

#151 Add find and delete on documentQuery, #144.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbOperations.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/criteria/CriteriaType.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/FindQuerySpecGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/AbstractDocumentDbQuery.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/DocumentDbQueryCreator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/DocumentDbQueryExecution.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/PartTreeDocumentDbQuery.java
Labels: feature

#156 Remove legacy find/delete on DocumentQuery, #144.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbOperations.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/criteria/Criteria.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/Criteria.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaDefinition.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaType.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQuery.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/Query.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/DocumentDbQueryCreator.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/common/TestConstants.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplateIllegalTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplatePartitionIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaUnitTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQueryUnitTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/query/QueryUnitTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/DocumentDBAnnotationIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/IntegerIdDomainRepositoryIT.java
Labels: Unit/Integration Test, enhancement

#157 Cleanup test repository folder, fix #155.
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/domain/Contact.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/AddressRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ContactRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/DocumentDBAnnotationIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/IntegerIdDomainRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/MemoRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/SquareRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/AddressRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/ContactRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/IntegerIdDomainRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/MemoRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/PersonRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/SquareRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/support/DocumentDbRepositoryFactoryBeanUnitTest.java
Labels: enhancement

#161 Fix or keyword query failure, fix #158.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQuery.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/domain/Project.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/ProjectRepository.java
Labels: Unit/Integration Test, bug

#162 Add IT test for keyword AND and OR
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/convert/MappingDocumentDbConverter.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/AddressRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/AddressRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/ProjectRepository.java
Labels: Unit/Integration Test

#163 Implement find all with sort, #146
  pom.xml
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbOperations.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/FindAllSortQuerySpecGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/Criteria.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQuery.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/support/SimpleDocumentDbRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/common/TestConstants.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/domain/Project.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/AddressRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositorySortIT.java
Labels: Unit/Integration Test, feature

#167 Refactor the DocumentQuery.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/FindAllSortQuerySpecGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/FindQuerySpecGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/DocumentDbQueryCreator.java
Labels: Defect, enhancement

#170 Add query method with sort 166
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/Constants.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbOperations.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/CountQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/FindAllSortQuerySpecGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/FindQuerySpecGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaType.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQuery.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/DocumentDbQueryCreator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/support/SimpleDocumentDbRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplateIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplateIllegalTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplatePartitionIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQueryUnitTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/MemoRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositorySortIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/ProjectRepository.java
Labels: Unit/Integration Test, feature

#172 Integrate find and count SqlQuerySpec generation, fix #169.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/CountQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/FindQuerySpecGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentDbPageRequest.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/DocumentDbQueryExecution.java
Labels: enhancement/refactor

#176 Use with builder for DocumentQuery, fix #175.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQuery.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/query/DocumentDbQueryCreator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/support/SimpleDocumentDbRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/common/PageTestUtils.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplateIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplateIllegalTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplatePartitionIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQueryUnitTest.java
Labels: enhancement/refactor

#180 Add suffix to testdb name, fix, #179.
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/common/TestConstants.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/TestRepositoryConfig.java
Labels: CI/CD, Unit/Integration Test

#177 refactor delete/find query, fix #148.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbOperations.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/support/SimpleDocumentDbRepository.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplateIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplateIllegalTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplatePartitionIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/DocumentDBAnnotationIT.java
Labels: enhancement/refactor

#183 Refactor Project Integration test.
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java
Labels: Defect

#182 Add keyword support for Greater than equal, #144.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaType.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/ProjectRepository.java
Labels: Unit/Integration Test, feature

#188 Fix defect of cross partition key flag, fix #186.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQuery.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQueryUnitTest.java
Labels: Defect

#184 Add keyword less and less equal, #144.
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaType.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/ProjectRepository.java
Labels: Unit/Integration Test, feature

#181 Add getCollectionLink without query, fix #152
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
Labels: Defect, enhancement/refactor

#190 Fix one defect of mvn command line eat error code.
  .travis.yml
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/DocumentDbTemplate.java
Labels: Defect

#191 Add keyword in 144
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/generator/AbstractQueryGenerator.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaType.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/query/DocumentQuery.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/core/query/CriteriaUnitTest.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/ProjectRepository.java
Labels: Unit/Integration Test, feature

#201 Fix telemetry proxy npe 200
  config/findbugs-exclude.xml
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/DocumentDbFactory.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/GetHashMac.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/MacAddress.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/TelemetryEventTracker.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/TelemetryProperties.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/common/TelemetryProxy.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/config/AbstractDocumentDbConfiguration.java
  src/main/java/com/microsoft/azure/spring/data/cosmosdb/config/DocumentDbConfigurationSupport.java
  src/test/java/com/microsoft/azure/spring/data/cosmosdb/config/AbstractDocumentDbConfigurationUnitTest.java
Labels: Defect, bug
